container:
    dockerfile: .cirrus/Dockerfile
    cpu: 8
    memory: 24G
    
env:
    TERM: xterm
    ANSI_GREEN: \033[32;1m
    ANSI_RESET: \033[0m
    ANSI_YELLOW: \033[33;1m
    ANSI_CLEAR: \033[0K
    ANSI_RED: \033[31;1m

build_task:
    timeout_in: 120m
    printenv_script: printenv
    build_script:
        - sudo bash build-package.sh -a $CIRRUS_TERMUX_ARCH libandroid-support
        - ls -l debs
    env:
        matrix:
            CIRRUS_TERMUX_ARCH: aarch64
            CIRRUS_TERMUX_ARCH: arm
            CIRRUS_TERMUX_ARCH: i686
            CIRRUS_TERMUX_ARCH: x86_64
